/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-04-09 20:44:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.material_002ddashboard_002dmaster.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_002dup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"../assets/img/apple-icon.png\">\r\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"../assets/img/favicon.png\">\r\n");
      out.write("  <title>\r\n");
      out.write("    ATLAS WORLD\r\n");
      out.write("  </title>\r\n");
      out.write("  <!--     Fonts and icons     -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700\" />\r\n");
      out.write("  <!-- Nucleo Icons -->\r\n");
      out.write("  <link href=\"../assets/css/nucleo-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"../assets/css/nucleo-svg.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"../assets/css/signup.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/42d5adcbca.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <!-- Material Icons -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons+Round\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- CSS Files -->\r\n");
      out.write("  <link id=\"pagestyle\" href=\"../assets/css/material-dashboard.css?v=3.0.1\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("  <div class=\"container position-sticky z-index-sticky top-0\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-12\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <main class=\"main-content  mt-0\">\r\n");
      out.write("    <section>\r\n");
      out.write("      <div class=\"page-header min-vh-100\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-7 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 start-0 text-center justify-content-center flex-column\">\r\n");
      out.write("              <div id=\"gradient\" class=\"position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center\" style=\"background-image: url('../assets/img/illustrations/signup.jpg'); background-size: cover;\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-4 col-lg-5 col-md-7 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-5\">\r\n");
      out.write("              <div class=\"card card-plain\">\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                  <h4 class=\"font-weight-bolder\">S'inscrire</h4>\r\n");
      out.write("                  <p class=\"mb-0\">Entrez votre numéro et votre nom pour vous inscrire</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <form role=\"form\" method=\"post\" action=\"http://localhost:8080/atlasweb/add\">\r\n");
      out.write("                    <div class=\"input-group input-group-outline mb-3\">\r\n");
      out.write("                      <label class=\"form-label\">Nom</label>\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" name=\"name\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-group input-group-outline mb-3\">\r\n");
      out.write("                      <label class=\"form-label\">Numéro telephone</label>\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\"  name=\"phonenumber\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-check form-check-info text-start ps-0\">\r\n");
      out.write("                      <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\" checked>\r\n");
      out.write("                      <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                        J'accepte <a href=\"javascript:;\" class=\"text-dark font-weight-bolder\">les termes et conditions</a>\r\n");
      out.write("                      </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0\" name=\"method\" value=\"signup\">S'inscrire</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-footer text-center pt-0 px-lg-2 px-1\">\r\n");
      out.write("                  <p class=\"mb-2 text-sm mx-auto\">\r\n");
      out.write("                    Vous avez deja un compte? \r\n");
      out.write("                    <a href=\"../pages/sign-in.jsp\" class=\"text-primary text-gradient font-weight-bold\">S'identifier</a>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </main>\r\n");
      out.write("  <!--   Core JS Files   -->\r\n");
      out.write("  <script src=\"../assets/js/core/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/core/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/plugins/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/plugins/smooth-scrollbar.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    var win = navigator.platform.indexOf('Win') > -1;\r\n");
      out.write("    if (win && document.querySelector('#sidenav-scrollbar')) {\r\n");
      out.write("      var options = {\r\n");
      out.write("        damping: '0.5'\r\n");
      out.write("      }\r\n");
      out.write("      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("  <!-- Github buttons -->\r\n");
      out.write("  <script async defer src=\"https://buttons.github.io/buttons.js\"></script>\r\n");
      out.write("  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->\r\n");
      out.write("  <script src=\"../assets/js/material-dashboard.min.js?v=3.0.1\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
